/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kim Geraldine
 */
public class backgroundAwal extends javax.swing.JPanel {

    /**
     * Creates new form backgroundAwal
     */
    
    private Image gambar;
    
    public backgroundAwal() {
        gambar = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/gambar/bg1.jpg"));
        MediaTracker media = new MediaTracker(this);
        media.addImage(gambar, 0);
        try {
            media.waitForID(0);
        } catch (InterruptedException ex) {
            Logger.getLogger(FotoAku.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        initComponents();
    }
    
     protected void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(gambar, 0, 0, getWidth(), getHeight(), this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
