/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;

/**
 *
 * @author Kim Geraldine
 */
public class panelTransparant extends javax.swing.JPanel {

    /**
     * Creates new form panelTransparant
     */
    
    private Color col;
    
    public panelTransparant() {
        
        setOpaque(false);
        col = new Color(getBackground().getRed(), getBackground().getGreen(), getBackground().getBlue(), 80);
        
        initComponents();
    }
    
    @Override
    public void setBackground(Color bg){
        super.setBackground(bg);
        col = new Color(getBackground().getRed(), getBackground().getGreen(), getBackground().getBlue(), 80);
        
        repaint();
    }

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D gr= (Graphics2D)g.create();
        gr.setColor(col);
        gr.fillRect(0, 0, getWidth(), getHeight());
        gr.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
